server:
  port: 9301

spring:
  application:
    name: humon-auth
  datasource:
    url: jdbc:postgresql://172.168.10.194:5432/humon-auth
    username: root
    password: root
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 50
      max-lifetime: 600000
    tomcat:
      test-on-borrow: true
      validation-query: SELECT 1
  jpa:
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    show-sql: true
    generate-ddl: true
    open-in-view: false
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        generate_statistics: false
        jdbc:
          batch_size: 1000
        order_inserts: true


# 接口文档配置
springdoc:
  api-docs:
    # 是否开启接口文档
    enabled: true
  #  swagger-ui:
  #    # 持久化认证数据
  #    persistAuthorization: true
  info:
    # 标题
    title: '标题：Humon_接口文档'
    # 描述
    description: '描述：...'
    # 版本
    version: '版本号：系统版本...'
    # 作者信息
    contact:
      name: Goya
      email: 773949603@qq.com
      url: https://gitee.com/dromara/RuoYi-Cloud-Plus
#  components:
    # 鉴权方式配置
#    security-schemes:
#      apiKey:
#        type: APIKEY
#        in: HEADER
#        name: ${sa-token.token-name}